// GENERATED by tools/ds5-scream/make_show.py — do not edit
// Burst choreography for the Grand Finale show (fwshow.wav)
#pragma once
#include <stdint.h>

typedef struct {
    uint16_t frame;      // 10ms content frame of the burst
    uint8_t r, g, b;
    uint8_t big;         // heavier haptic + longer fade
} ds5_show_event_t;

static const ds5_show_event_t ds5_show_events[] = {
    { 220, 255, 30, 30, 1 },
    { 555, 255, 255, 255, 0 },
    { 837, 60, 90, 255, 0 },
    { 1070, 255, 30, 30, 0 },
    { 1324, 255, 255, 255, 0 },
    { 1648, 60, 90, 255, 1 },
    { 1804, 255, 150, 20, 1 },
    { 2112, 255, 30, 30, 0 },
    { 2187, 255, 255, 255, 0 },
    { 2262, 60, 90, 255, 0 },
    { 2327, 255, 255, 255, 1 },
    { 2529, 255, 150, 20, 1 },
};
#define DS5_SHOW_EVENT_COUNT 12
